---
configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_repo_version: master # Replace with your default branch
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
>>>>>>> origin/master
  - hudochenkov/sshpass/sshpass
  - telnet
  - vlc
  - kubectl

homebrew_taps: []
=======
=======
>>>>>>> origin/master
  - helm
  - macfuse
  - ext4fuse
  - fluxcd/tap/flux
  - gh
  - lens
  - datreeio/datree/datree
  - sops
  - age
  - 1password-cli
  - virt-viewer
  # brew install --no-quarantine weakauras-companion

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - datreeio/datree
  - jeffreywildman/homebrew-virt-manager
>>>>>>> 84502c9 ((update) Include config over time to bring up to current state)
>>>>>>> origin/master

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - licecap
  - sequel-ace
  - slack
  - sublime-text
  - transmit

=======
# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 443987910, name: "1Password" }
>>>>>>> 84502c9 ((update) Include config over time to bring up to current state)
=======
# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 443987910, name: "1Password" }
>>>>>>> origin/master
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages:
  - "xkcdpass"
  
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "Theme - Cobalt2"
  - "TrailingSpaces"
  - "WordingStatus"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
